export enum LayoutClassName {
    LoginBtn = 'login-btn',
    LogoutBtn = 'logout-btn',
    CurrencyBtn = 'currency-btn',
    LanguageBtn = 'language-btn',
    ShoppingThemeBtn = 'shopping-theme-btn',
    BurgerShoppingBtnColor = 'burger-shopping-btn-color',
    BurgerShoppingBtnOutline = 'burger-shopping-btn-outline',
    CartBtn = 'cart-btn',
    BookmarkProducts = 'bookmark-products',
    CompareList = 'compare-list',    
    YourOrders = 'user-orders',
    GlobalSearchInput = 'global-search-input',
    GlobalSearchConfirmBtn = 'global-search-confirm-btn',
    GlobalSearchCloseBtn = 'global-search-close-btn',
    ProductSearchCard = 'product-search-card',
    ProductSearchCardTitle = 'product-search-card-title',
    ViewSearchBtn = 'view-search-btn',
    LangChangedText = 'lang-changed-text',
    CurrencyChanged = 'currency-changed',    
    EsaLogo = 'esa-logo',
    TourBtn = 'tour-btn',

    // Index
    ShoppingNowBtn = 'shopping-now-btn',
}